name: Node.js CI Backend

on:
  pull_request:
    branches: [ "AP-27-Set-up-continuous-integration-on-GitHub" ]
defaults:
  run:
    working-directory: api
env:
  NODE_ENV: test
jobs:
  buildStepJob:
    runs-on: ubuntu-latest
    environment: test
    strategy:
      matrix:
        node-version: [ 18.x ]
        mongodb-version: [ '5.0' ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }} and install packages
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install pm2@latest -g #install pm2 global
      - name: Create .env file
        run: |
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env.test.local
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.test.local
          echo "NODE_ENV=test" >> .env.test.local
      - name: Install dependencies
        run: npm ci
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Test backend
        run: npm start && npm test