# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "AP-27-Set-up-continuous-integration-on-GitHub" ]

jobs:
  buildStepJob:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [ 18.x ]
          mongodb-version: [ '5.0' ]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
        - name: Git checkout
          uses: actions/checkout@v3

        - name: Start MongoDB
          uses: supercharge/mongodb-github-action@1.8.0
          with:
            mongodb-version: ${{ matrix.mongodb-version }}

        - name: Use Node.js ${{ matrix.node-version }} and install packages
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - name: install api folder packages
          run: cd api && npm ci
        - name: install frontend folder packages
          run: cd frontend && npm ci
        - name: start backend
          run: cd api && JWT_SECRET=SUPER_SECRET npm start
        - name: start frontend
          run: cd frontend && JWT_SECRET=SUPER_SECRET npm start


